locale                   : "en-US"
site_theme               : "default"
title                    : "kamilka"
title_separator          : "-"
name                     : &name "Mohamed Kamil El Kouarti"
description              : &description "Soy Mohamed, estudiante de ciberseguridad. En esta página compartiré lo que aprendo, creo o descubro, como un blog de notas personal."
url                      : "https://k4m1lk4.github.io/mohamed_kamil.github.io"
baseurl                  : ""
repository               : "K4M1LK4/mohamed_kamil.github.io"

author:
  avatar           : "ocho_pfp.png"
  name             : *name
  bio              : "Cybersecurity student"
  location         : "Spain"
  email            : "kouartimohamedkamil@gmail.com"
  github           : "K4M1LK4"
  orcid            : "http://orcid.org/0000-0000-0000-0000"  # cámbialo si tienes uno real
  googlescholar    : "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
  pubmed           : "https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"
  youtube          : "K4M1LK4"

# Publication Categories
publication_category:
  books:
    title: 'Books'
  manuscripts:
    title: 'Journal Articles'    
  conferences:
    title: 'Conference Papers'

# Site Settings
words_per_minute         : 160
read_more                : "disabled"
future                   : true
talkmap_link             : false

comments:
  provider               : false

atom_feed:
  hide                   : false

# SEO
google_site_verification :
bing_site_verification   :
yandex_site_verification :

# Social Sharing
twitter:
  username               : 
facebook:
  username               :

social:
  type                   : Person
  name                   : *name
  links:
    - "https://github.com/K4M1LK4"
    - "https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
    - "https://youtube.com/@K4M1LK4"

# Analytics
analytics:
  provider               : false

# Include/Exclude
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-*"
  - .asset-cache
  - .github
  - .sass-cache
  - node_modules
  - vendor
  - README
  - tmp

keep_files:
  - .git

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Markdown
markdown: kramdown
highlighter: rouge
excerpt_separator: "\n\n"

kramdown:
  input: GFM

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
  notes:
    output: true
    permalink: /collection/:path/


# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true

# Sass
sass:
  sass_dir: _sass
  style: compressed

# Output
permalink: /:categories/:title/
timezone: Europe/Madrid

# Plugins
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
